// Generated by CoffeeScript 1.4.0
var util;

util = require('./util');

if (!document.body.contains) {
  HTMLElement.prototype.contains = function(node) {
    return !!(this.compareDocumentPosition(node) & 16);
  };
}

/*
  Add support for insertAdjacentHTML for Firefox < 8
  Based on insertAdjacentHTML.js by Eli Grey, http://eligrey.com
*/


if (!document.body.insertAdjacentHTML) {
  HTMLElement.prototype.insertAdjacentHTML = function(position, html) {
    var parent, ref;
    position = position.toLowerCase();
    ref = this;
    parent = ref.parentNode;
    switch (position) {
      case 'beforeend':
        return ref.appendChild(util.createFragment(ref, html));
      case 'beforebegin':
        return parent.insertBefore(util.createFragment(parent, html), ref);
      case 'afterend':
        return parent.insertBefore(util.createFragment(parent, html), ref.nextSibling);
      case 'afterbegin':
        return ref.insertBefore(util.createFragment(ref, html), ref.firstChild);
    }
  };
}
