// Generated by CoffeeScript 1.4.0
var Item, ItemRange, Saddle, doc, methodName, _ref,
  __hasProp = {}.hasOwnProperty;

Item = require('./Item');

ItemRange = require('./ItemRange');

doc = document;

Saddle = (function() {
  var getCachedItem;

  getCachedItem = function(id, map) {
    var item;
    if ((item = map[id]) && doc.contains(item.el || item)) {
      return item;
    }
  };

  function Saddle(options) {
    options || (options = {});
    this.prefix = options.prefix || '$';
    this.useTags = !!options.useTags;
    this.itemsMap = {};
    this.markersMap = {};
    this._id = 0;
  }

  Saddle.prototype._updateMarkers = function() {
    var comment, commentIterator, markersMap;
    this.markersMap = markersMap = {};
    commentIterator = doc.createTreeWalker(doc.body, 128, null, false);
    while (comment = commentIterator.nextNode()) {
      markersMap[comment.data] = comment;
    }
    return markersMap;
  };

  Saddle.prototype.get = function(id) {
    var comment, el, item, itemsMap, markersMap;
    itemsMap = this.itemsMap;
    markersMap = this.markersMap;
    if (item = getCachedItem(id, itemsMap)) {
      return item;
    }
    if ((el = doc.getElementById(id)) && el.tagName !== 'COMMENT') {
      return itemsMap[id] = new Item(el);
    }
    if (!(comment = getCachedItem(id, markersMap))) {
      markersMap = this._updateMarkers();
      comment = markersMap[id];
    }
    if (comment) {
      return itemsMap[id] = new ItemRange(comment, markersMap[this.prefix + id]);
    }
  };

  Saddle.prototype.clear = function() {
    this.itemsMap = {};
    this.markersMap = {};
    this._id = 0;
  };

  Saddle.prototype.uid = function() {
    return this.prefix + (this._id++).toString(36);
  };

  Saddle.prototype.getMarkerTpl = function() {
    if (this.useTags) {
      return function(id) {
        return ["<comment id=" + id + "/>", "<comment id=" + (this.prefix + id) + "/>"];
      };
    } else {
      return function(id) {
        return ["<!--" + id + "-->", "<!--" + (this.prefix + id) + "-->"];
      };
    }
  };

  Saddle.prototype.prepend = function(id, html) {
    this.insert(id, html, 0);
  };

  return Saddle;

})();

_ref = Item.prototype;
for (methodName in _ref) {
  if (!__hasProp.call(_ref, methodName)) continue;
  Saddle.prototype[methodName] = (function(methodName) {
    return function(id, arg1, arg2, arg3) {
      var _ref1;
      return (_ref1 = this.get(id)) != null ? _ref1[methodName](arg1, arg2, arg3) : void 0;
    };
  })(methodName);
}

module.exports = Saddle;
