// Generated by CoffeeScript 1.4.0
var Item, ItemRange, Saddle, methodName, _ref,
  __hasProp = {}.hasOwnProperty;

Item = require('./Item');

ItemRange = require('./ItemRange');

module.exports = Saddle;

Saddle = (function() {

  function Saddle(options) {
    ItemRange.prefix = options.prefix || '$';
    ItemRange.useTags = !!options.useTags;
    this._id = 0;
  }

  return Saddle;

})();

_ref = Item.prototype;
for (methodName in _ref) {
  if (!__hasProp.call(_ref, methodName)) continue;
  Saddle.prototype[methodName] = (function(methodName) {
    return function(id, arg1, arg2, arg3) {
      return new Item(id)[methodName](arg1, arg2, arg3);
    };
  })(methodName);
}
