// Generated by CoffeeScript 1.4.0
var Item, ItemRange, Saddle, methodName, _ref,
  __hasProp = {}.hasOwnProperty;

Item = require('./Item');

ItemRange = require('./ItemRange');

Saddle = (function() {
  var getMarkerTpl;

  function Saddle(options) {
    if (options == null) {
      options = {};
    }
    this.prefix = ItemRange.prefix = options.prefix || '$';
    this.useTags = ItemRange.useTags = !!options.useTags;
    this._id = 0;
  }

  Saddle.prototype.clear = function() {
    Item.clear();
    return ItemRange.clear();
  };

  Saddle.prototype.uid = function() {
    return this.prefix + (this._id++).toString(36);
  };

  getMarkerTpl = function() {
    if (this.useTags) {
      return function(id) {
        return ["<comment id=" + id + "/>", "<comment id=" + (this.prefix + id) + "/>"];
      };
    } else {
      return function(id) {
        return ["<!--" + id + "-->", "<!--" + (this.prefix + id) + "-->"];
      };
    }
  };

  return Saddle;

})();

_ref = Item.prototype;
for (methodName in _ref) {
  if (!__hasProp.call(_ref, methodName)) continue;
  Saddle.prototype[methodName] = (function(methodName) {
    return function(id, arg1, arg2, arg3) {
      var _ref1;
      return (_ref1 = Item.get(id)) != null ? _ref1[methodName](arg1, arg2, arg3) : void 0;
    };
  })(methodName);
}

module.exports = Saddle;
