// Generated by CoffeeScript 1.4.0
var ItemRange;

ItemRange = (function() {
  var commentsMap, createRange, doc;

  ItemRange.prefix = '$';

  ItemRange.useTags = false;

  doc = document;

  createRange = function() {
    return doc.createRange();
  };

  commentsMap = {};

  ItemRange.get = function(id) {
    var comment, commentIterator;
    if ((comment = commentsMap[id]) && doc.contains(comment)) {
      return new ItemRange(comment, id);
    }
    commentsMap = {};
    commentIterator = doc.createTreeWalker(doc.body, 128, null, false);
    while (comment = commentIterator.nextNode()) {
      commentsMap[comment.data] = comment;
    }
    if (comment = commentsMap[id]) {
      return new ItemRange(comment, id);
    }
  };

  ItemRange.clear = function() {
    return commentsMap = {};
  };

  function ItemRange(start, id) {
    var end, range;
    end = commentsMap[ItemRange.prefix + id];
    this.range = range = createRange();
    range.setStartAfter(start);
    range.setEndBefore(end);
  }

  ItemRange.prototype.setHtml = function(html) {
    var range;
    range = this.range;
    range.deleteContents();
    range.insertNode(range.createContextualFragment(html));
  };

  ItemRange.prototype.append = function(html) {
    var endContainer, nodeAfterRange, range;
    range = this.range;
    endContainer = range.endContainer;
    nodeAfterRange = endContainer.childNodes[range.endOffset];
    nodeAfterRange.insertAdjacentHTML('beforebegin', html);
  };

  ItemRange.prototype.insert = function(html, index) {
    var indexNode, range;
    range = this.range;
    indexNode = range.startContainer.childNodes[range.startOffset + index];
    indexNode.insertAdjacentHTML('beforebegin', html);
  };

  ItemRange.prototype.remove = function(index) {
    var range, startContainer;
    range = this.range;
    startContainer = range.startContainer;
    startContainer.removeChild(startContainer.childNodes[range.startOffset + index]);
  };

  ItemRange.prototype.move = function(from, to, howMany) {
    var before, child, frag, offset, range, startContainer;
    if (howMany == null) {
      howMany = 1;
    }
    range = this.range;
    startContainer = range.startContainer;
    offset = range.startOffset;
    child = startContainer.childNodes[from + offset];
    before = startContainer.childNodes[to + offset];
    if (howMany === 1) {
      startContainer.insertBefore(child, before);
    } else {
      frag = doc.createDocumentFragment();
      while (howMany--) {
        frag.appendChild(child);
        child = child.nextSibling();
      }
      startContainer.insertBefore(frag, before);
    }
  };

  return ItemRange;

})();

module.exports = ItemRange;
