// Generated by CoffeeScript 1.4.0
var Item, ItemSVG,
  __hasProp = {}.hasOwnProperty,
  __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

Item = require('./Item');

module.exports = ItemSVG;

ItemSVG = (function(_super) {

  __extends(ItemSVG, _super);

  function ItemSVG() {
    return ItemSVG.__super__.constructor.apply(this, arguments);
  }

  return ItemSVG;

})(Item);
