// Generated by CoffeeScript 1.4.0
var ItemRange, util;

util = require('./util');

ItemRange = (function() {
  var doc;

  doc = document;

  function ItemRange(start, end) {
    var parent, svg;
    this.start = start;
    this.end = end;
    this.el = start;
    this.range = util.createRange();
    this._updateRange();
    parent = start.parentNode;
    svg = parent.ownerSVGElement || parent.tagName.toLowerCase() === 'svg';
    this.svgRoot = svg && (parent.ownerSVGElement || parent);
  }

  ItemRange.prototype._createFrag = function(html) {
    return util.createFragment(this.svgRoot || this.range, html);
  };

  ItemRange.prototype._updateRange = function() {
    var range;
    range = this.range;
    range.setStartAfter(this.start);
    range.setEndBefore(this.end);
  };

  ItemRange.prototype.setHtml = function(html) {
    var fragment, range;
    range = this.range;
    range.deleteContents();
    fragment = range.insertNode(this._createFrag(html));
    this._updateRange();
  };

  ItemRange.prototype.append = function(html) {
    this.insert(html);
  };

  ItemRange.prototype.insert = function(html, index) {
    var containerIndex, nodeInsertBefore, range, startContainer;
    range = this.range;
    containerIndex = range.endOffset - range.startOffset > index ? range.startOffset + index : range.endOffset;
    startContainer = range.startContainer;
    nodeInsertBefore = startContainer.childNodes[containerIndex];
    startContainer.insertBefore(this._createFrag(html), nodeInsertBefore);
    this._updateRange();
  };

  ItemRange.prototype.remove = function(index) {
    var range;
    range = this.range;
    util.rmChild(range.startContainer, range.startOffset + index);
    this._updateRange();
  };

  ItemRange.prototype.move = function(from, to, howMany) {
    var endOffset, indexTo, offset, range;
    if (howMany == null) {
      howMany = 1;
    }
    range = this.range;
    offset = range.startOffset;
    endOffset = range.endOffset;
    indexTo = offset + (to >= from ? to + howMany : to);
    if (indexTo > endOffset) {
      indexTo = endOffset;
    }
    util.move(range.startContainer, offset + from, indexTo, howMany);
    this._updateRange();
  };

  return ItemRange;

})();

module.exports = ItemRange;
