// Generated by CoffeeScript 1.4.0
var doc;

doc = document;

module.exports = {
  rangeIns: function(range, html, index) {
    var nodeInsertBefore, startContainer;
    startContainer = range.startContainer;
    nodeInsertBefore = startContainer.childNodes[index!=null ? range.startOffset + index : range.endOffset];
    startContainer.insertBefore(range.createContextualFragment(html), nodeInsertBefore);
  },
  rmChild: function(el, index) {
    el.removeChild(el.childNodes[index]);
  },
  move: function(el, from, toIndex, howMany) {
    var before, child, childNodes, frag, next;
    if (howMany == null) {
      howMany = 1;
    }
    childNodes = el.childNodes;
    child = childNodes[from];
    before = childNodes[toIndex] || null;
    if (howMany === 1) {
      el.insertBefore(child, before);
    } else {
      frag = doc.createDocumentFragment();
      while (howMany--) {
        next = child.nextSibling;
        frag.appendChild(child);
        child = next;
      }
      el.insertBefore(frag, before);
    }
  }
};
