// Generated by CoffeeScript 1.4.0
var RangeImplementation, doc;

RangeImplementation = require('./RangeShim');

doc = document;

module.exports = {
  createRange: function() {
    return new RangeImplementation;
  },
  rmChild: function(el, index) {
    var child;
    if (child = el.childNodes[index]) {
      el.removeChild(child);
    }
  },
  move: function(el, from, toIndex, howMany) {
    var before, child, childNodes, frag, next;
    if (howMany == null) {
      howMany = 1;
    }
    childNodes = el.childNodes;
    child = childNodes[from];
    before = childNodes[toIndex] || null;
    if (howMany === 1) {
      el.insertBefore(child, before);
    } else {
      frag = doc.createDocumentFragment();
      while (howMany--) {
        next = child.nextSibling;
        frag.appendChild(child);
        child = next;
      }
      el.insertBefore(frag, before);
    }
  },
  createFragment: function(rangeOrParent, html) {
    var range;
    if (rangeOrParent.nodeType) {
      range = this.createRange();
      range.setStartAfter(rangeOrParent);
    } else {
      range = rangeOrParent;
    }
    return range.createContextualFragment(html);
  }
};
